name: Rust CI / CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check version
      run: cargo version

    - name: Run tests
      run: cargo test

  build-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check version
        run: cargo version

      - name: Run tests
        run: cargo test
